image: ubuntu:18.04

services:
  - mdillon/postgis:10
  - elasticsearch:5
  #- redis:latest

variables:
  POSTGRES_DB: landmatrix
  POSTGRES_USER: landmatrix
  POSTGRES_PASSWORD: landmatrix

before_script:
  - export LANG=C.UTF-8
  - ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime
  - apt-get update
  - apt-get install -y git python3-pip gdal-bin
  - pip3 install pipenv
  - pipenv install --dev
  - echo -e " DJANGO_SETTINGS_MODULE=config.settings.dev\nDATABASE_URL=postgis://landmatrix:landmatrix@mdillon__postgis/landmatrix" > .env
  - pipenv run doit migrate


test:
  script:
    - pipenv run coverage run --source='.' manage.py test --settings=config.settings.ci --exclude-tag integration
    - pipenv run coverage report
