image: sinntern/ubuntu_for_django:latest

variables:
  LANG: C.UTF-8
  POSTGRES_DB: landmatrix
  POSTGRES_USER: landmatrix
  POSTGRES_PASSWORD: landmatrix
  STAGING_HOST: dev.landmatrix.org
  STAGING_USER: landmatrix
  PRODUCTION_HOST: landmatrix.org
  PRODUCTION_USER: landmatrix
  DJANGO_SETTINGS_MODULE: config.settings.dev
  DATABASE_URL: "postgis://landmatrix:landmatrix@mdillon__postgis/landmatrix"
  ELASTICSEARCH_URL: "http://elasticsearch"

stages:
  - test
  - deploy

formatting and linting:
  stage: test
  script:
    - poetry install
    - yarn install --frozen-lockfile
    - black . --check
    - poetry run pylint config  -d unused-wildcard-import,unused-import,wildcard-import
    - poetry run pylint apps --exit-zero

tests and coverage:
  stage: test
  services:
    - mdillon/postgis:10
    - elasticsearch:5
  script:
    - poetry install
    - yarn install --frozen-lockfile
    - poetry run doit -n 4 update
    - poetry run pytest
  coverage: /^TOTAL.*\s+(\d+\%)$/

deploy to staging:
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - echo "$STAGING_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - |
      ssh $STAGING_USER@$STAGING_HOST << E=O=F
      mv maintenance.html_ maintenance.html
      cd ~/htdocs
      git checkout master
      git pull
      poetry install -E production
      poetry run doit update
      sudo /bin/systemctl restart django-dev.landmatrix.org.service
      cd ~
      mv maintenance.html maintenance.html_
      E=O=F
  only:
    - master

deploy to production:
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - echo "$PRODUCTION_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - |
      ssh $PRODUCTION_USER@$PRODUCTION_HOST << E=O=F
      mv maintenance.html_ maintenance.html
      cd ~/htdocs
      git checkout production
      git pull
      poetry install --no-dev -E production
      poetry run doit update
      sudo /bin/systemctl restart django-landmatrix.org.service
      cd ~
      mv maintenance.html maintenance.html_
      E=O=F
  only:
    - production
