[tool.poetry]
name = "landmatrix"
version = "0.1.0"
license = "AGPL-3.0+"
authors = [
  "Simon Liedtke <simon.liedtke@gmail.com>",
  "Andreas Nüßlein <andreas@nuessle.in>"
]
readme = 'README.md'
description = "LandMatrix"

[tool.poetry.dependencies]
python = "^3.6"
Django = "<2.3"
wagtail = "<2.8"

simplejson = "*"
pyelasticsearch = {git = "https://github.com/sinnwerkstatt/pyelasticsearch", branch = "batteriesincluded" }

# greennewdeal
django-reversion = "*"
elasticsearch-dsl = ">=7.0.0,<8.0.0"
django-elasticsearch = "^7.0.2"
django-webpack-loader = "^0.7.0"
geojson-rewind = "^0.2.0"
ariadne = "^0.10.0"
wagtail-apiimagerendition = "^0.1b0"

psycopg2-binary = "*"
redis = "*"
python-memcached = "*"

djangorestframework = "*"
djangorestframework-gis = "*"
drf-yasg = "*"
packaging = "*"
#django-rest-swagger = "*"
django-crispy-forms = "*"
django-environ = "*"
django-file-resubmit = "*"
django-jstemplate = "*"
django-modeltranslation = "*"
django-contrib-comments = "*"
django-threadedcomments = "*"
django-bootstrap3-datetimepicker-2 = "*"
django-impersonate = "*"
django-multiselectfield = "*"
django-recaptcha = "*"
django-registration = "*"
django-simple-history = "*"
django-wkhtmltopdf = "*"

wagtail-blog = "*"
wagtail-modeltranslation = "*"

geojson = "<2"
unicodecsv = "*"
openpyxl = "*"
tweepy = "*"
country-bounding-boxes = "*"
python-dateutil = "*"


#plumbing
doit = "*"
celery = "*"
libsass = "*"
django-prometheus = "*"
gunicorn = { version = "*", optional = true }
raven = { version = "*", optional = true }



[tool.poetry.dev-dependencies]
ipdb = "*"
black = { version = "*", allow-prereleases = true }
mypy = "*"
django-livereload = "*"
django-extensions = "*"
pytest-django = "*"
pytest-cov = "*"
pylint = "*"
pylint-django = "*"
pygments = "*"
mkdocs = "*"

[tool.poetry.extras]
production = ["gunicorn", "raven"]


[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | migrations
  | static-collected
  | node_modules
)/
'''
#
[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = false
line_length = 88
known_first_party = 'apps'
known_django = 'celery,django,django_registration,wagtail'
default_section = 'THIRDPARTY'
sections = 'FUTURE,STDLIB,THIRDPARTY,DJANGO,FIRSTPARTY,LOCALFOLDER'
no_lines_before = 'LOCALFOLDER,DJANGO'
